Entrega1AberoCavalli/Entrega1AberoCavalli/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path("FoodTaster/", include('FoodTaster.urls')),
]

Entrega1AberoCavalli/FoodTaster/urls.py
from django.urls import path
from FoodTaster import views

app_name='FoodTaster'
urlpatterns = [
    path('', views.index, name='home'),
    
    path('dishes', views.dish_list, name='dish-list'),
    path('dish/<int:pk>', views.dish, name='dish-detail'),
    path('dish/add', views.dish_add, name='dish-add'),

    path('recipes', views.recipe, name='recipe-list'),
    path('recipes/add/<int:pk>', views.recipe_add, name='recipe-add'),

    path('ingredient', views.ingredient, name='ingredient-list'),
    path('ingredient/add', views.ingredient_add, name='ingredient-add'),

    path('search-recipes', views.search, name='search-recipe'),
]

Entrega1AberoCavalli/FoodTaster/models.py
from django.db import models

# Create your models here.
class Dish(models.Model):
    name=models.CharField(max_length=60)
    description=models.CharField(max_length=200)
    rating=models.FloatField()

    def __str__(self):
        return f'{self.name}'


class Ingredient(models.Model):
    name=models.CharField(max_length=100)
    description=models.CharField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name}'


class Dish_Ingredient(models.Model):
    dishCode=models.IntegerField(default=0)
    recipeCode=models.IntegerField(default=0)
    ingredientCode=models.IntegerField(default=0)
    ingredientAmount=models.CharField(max_length=100)

    def __str__(self):
        return ''


class Recipe(models.Model):
    name=models.CharField(max_length=100, null=True)
    dishCode=models.IntegerField(null=True)
    steps=models.CharField(max_length=400, null=True)

    def __str__(self):
        return f'{self.name}'

    def desc(self):
        return f'{self.description}'

Entrega1AberoCavalli/FoodTaster/forms.py
from optparse import Values
from pydoc import describe
import re
from unicodedata import name
from django import forms
from django.forms import ModelForm
from FoodTaster.models import Recipe, Dish, Ingredient

class DishesForm(forms.Form):
    name=forms.CharField(label="Nombre del Plato", max_length=60, required=True)
    description=forms.CharField(label="Descripcion",max_length=200, min_length=10, required=True)
    rating=forms.FloatField(label="Dale un puntaje del 1 al 10", max_value=10, min_value=1, required=False)


class RecipesForm(forms.Form):
    name=forms.CharField(label="Nombre", max_length=100, required=True)
    dishCode=forms.ModelChoiceField(queryset=Dish.objects.all().order_by('pk'), required=True)
    steps=forms.CharField(label="Receta", max_length=400, required=True)


class IngredientForm(forms.Form):
    name=forms.CharField(label="Nombre", max_length=100, required=True)
    description=forms.CharField(label="Description", max_length=200, required=False)

Entrega1AberoCavalli/FoodTaster/views.py
from multiprocessing import context
from re import S
from ssl import HAS_TLSv1_2
from unicodedata import name
#from typing_extensions import Required
from urllib import request
from django.shortcuts import render
from FoodTaster.forms import RecipesForm
from FoodTaster.models import Dish, Recipe, Ingredient, Dish_Ingredient
from FoodTaster.forms import DishesForm, RecipesForm, IngredientForm


# Create your views here.
def index(request):
    dishes = Dish.objects.all()[:3]

    context_dict = {
        'dishes': dishes
    }

    return render(request,
                  context=context_dict,
                  template_name="FoodTaster/home.html")


def search(request):
    context_dict = dict()

    print("imprimo request: ")
    print(request)
    if request.method == 'GET':
        try:
            if request.GET['text_search']:
                search_param = request.GET['text_search']
                recipe = Recipe.objects.filter(name__contains=search_param)
        except:
            recipe = Recipe.objects.all()
        
    context_dict = {
        'recipes': recipe,
    }

    return render(
        request=request,
        context=context_dict,
        template_name="FoodTaster/searchRecipes.html",
    )


#Dishes
def dish(request, pk):
    dishes = Dish.objects.filter(pk=pk)
    #Se obtiene el la info general del plato
    #dish_info = dish.values('name', 'description')[0] 
    #Para el plato obtengo las recetas
    recipes = Recipe.objects.filter(dishCode=pk)

    context_dict = {
        'pk' : pk,
        'dishes' : dishes,
        'recipes' : recipes,
    }

    return render(
        request=request,
        context=context_dict,
        template_name="FoodTaster/dish_detail.html"
    )


def dish_list(Request):
    dishes = Dish.objects.all()

    context_dict = {
        'Dishes' : dishes,
    }

    return render(
        request=Request,
        context=context_dict,
        template_name="FoodTaster/dish_list.html")


def dish_add(Request):
    if Request.method == "POST":
        dish_form = DishesForm(Request.POST)
        if dish_form.is_valid():

            data  = dish_form.cleaned_data

            dish = Dish(name=data['name'], description=data['description'], 
            rating=data['rating'])

            dish.save()

            recipes = Recipe.objects.filter(dishCode=dish.pk)

            context_dict = {
                'dish' : dish,
                'recipes' : recipes,
            }

            return render(  request=Request, 
                            context= context_dict,
                            template_name="FoodTaster/dish_detail.html"
                        )

    form_title = "Receta"
    form_description = "Ingrese el nombre del plato de la receta, y una descripcion"
    dish_form = DishesForm(Request.POST)

    context_dict = {
        'form' : dish_form,
        'form_title' : form_title,
        'form_description' : form_description,
    }

    return render(request=Request, 
                context=context_dict,
                template_name="FoodTaster/genericForm.html"
    )


#Recipe
def recipe(Request):
    recipe = Recipe.objects.all()

    context_dict = {
        'recipe' : recipe,
    }

    return render(
       request=Request,
       context=context_dict,
       template_name="FoodTaster/recipe_list.html"
    )


def recipe_add(Request, pk=0):
    if Request.method == "POST":    
        recipe = Recipe(name=Request.POST['name'], dishCode=Request.POST['dishCode'],
            steps=Request.POST['steps'])
    
        recipe.save()

        recipes = Recipe.objects.all()

        context_dict = {
            'recipes' : recipes,
            'recipe' : recipe,
        }

        return render(
            request=Request,
            context=context_dict,
            template_name="FoodTaster/recipe_detail.html"
        )
    
    form_title = "Receta"
    form_description = "Ingrese el nombre de la Receta y su paso a paso"
    recipe_form = RecipesForm(Request.POST)

    recipe_form.dishCode = pk

    context_dict = {
        'form' : RecipesForm,
        'form_title' : form_title,
        'dish_code' : pk,
        'form_description' : form_description,
    }

    return render(request=Request, 
                context=context_dict,
                template_name="FoodTaster/recipesForm.html"
    )


#Ingredient
def ingredient(Request):
    ingredient = Ingredient.objects.all()

    context_dict = {
        'ingredients' : ingredient,
    }

    return render(
       request=Request,
       context=context_dict,
       template_name="FoodTaster/ingredient_list.html"
    )

def ingredient_add(Request):
    if Request.method == "POST":
        ingredient = Ingredient(name=Request.POST['name'], 
        description=Request.POST['description'])
    
        ingredient.save()

        context_dict = {
            'ingredient' : ingredient,
        }

        return render(
            request=Request,
            context=context_dict,
            template_name="FoodTaster/ingredient_detail.html"
        )
    
    form_title = "ingrediente"
    form_description = "Ingrese el nombre del ingrediente"
    ingredient_form = IngredientForm(Request.POST)

    context_dict = {
        'form' : IngredientForm,
        'form_title' : form_title,
        'form_description' : form_description,
    }

    return render(request=Request, 
                context=context_dict,
                template_name="FoodTaster/genericForm.html"
    )

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/dish.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<h2>Lista de Platos</h2>
<a class="card_custom" href="{% url 'FoodTaster:dish-add' %}">Ingresar nuevo plato</a>
<hr></hr>
<ul>
    {% for dish in dish_list %}
    <li>
        {{dish}}
        (
        <a href="{% url 'FoodTaster:dish-detail' dish.id %}">
            <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
        </a>
        |
        <a href="{% url 'FoodTaster:dish-update' dish.id %}">
            <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
        </a>
        |
        <a href="{% url 'FoodTaster:dish-delete' dish.id %}">
            <i class="fa fa-trash" style="color: rgb(0, 0, 100);"> </i>
        </a>
        )
    </li>
    {% endfor %}
</ul>

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/dish_detail.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

{% for dish in dishes %}

    <p><h3 class="mb-1 ms-xl-1">Nombre: {{ dish.name }}</h3></p>
    <p class="mb-1 ms-xl-2">{{ dish.description }} <br></p>

    <div>                                 
        <p><a class="btn2 btn-primary" href="{% url 'FoodTaster:recipe-add' pk  %}">Agregar receta</a></p>
    </div>
    
{% endfor %}

{% if recipes %}
    <ul>
        {% for recipe in recipes %}
            <li>
                <h4>{{ recipe.name }}</h4>
                <p><br><small>{{ recipe.description }}</small></p>
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/dish_form.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<h2>Formulario para guardar/editar plato</h2>
<hr></hr>

<form action="" method="POST">
    {% csrf_token %}
    <p>
    <table>
        {{ form.as_table }}
    </table>
    </p>
    <p>
        <input type="submit" class="btn btn-primary" value="Guardar" />
    </p>
</form>

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/dish_list.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<h2>Lista de Platos</h2>
<a class="card_custom" href="{% url 'FoodTaster:dish-add' %}">Crear nuevo Plato</a>
<hr></hr>
<ul>
    {% for dish in dish_list %}
    <li>
        {{dish}}
        (
        <a href="{% url 'FoodTaster:dish-detail' dish.id %}">
            <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
        </a>
        |
        <a href="{% url 'FoodTaster:dish-update' dish.id %}">
            <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
        </a>
        |
        <a href="{% url 'FoodTaster:dish-delete' dish.id %}">
            <i class="fa fa-trash" style="color: rgb(0, 0, 100);"> </i>
        </a>
        )
    </li>
    {% endfor %}
</ul>

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/genericForm.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<h2>{{ form_title }}</h2>
<hr></hr>

<div><p>{{ form_description }}</p></div>

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_p }}
    </table>

    <input type="submit" class="btn btn-primary" value="Confirmar"/>
</form>

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/home.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<div class="list-group">
    {% for dish in dishes %}
    <ul> 
        <a href="{% url 'FoodTaster:dish-detail' dish.id %}" class="list-group-item list-group-item-action flex-column align-items-start home-card">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{ dish.name }}</h5>
        </div>
        </a>
        <div class="d-flex w-100 justify-content-between" style="background-color: white;">
        <p class="mb-1 ms-xl-2" style="color:black;">{{dish.description}}</p>
        </div>
    </ul>
    {% endfor %}
  </div>

  
{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'FoodTaster/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'FoodTaster/css/styles.css' %}" rel="stylesheet" />
        <!-- Awesome fonts -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top justify-content-center">
            <div class="container">
                <a class="navbar-brand" href="{% url 'FoodTaster:home' %}">Home</a>
                <a class="navbar-brand" href="{% url 'FoodTaster:dish-list' %}">Platos</a>
                <a class="navbar-brand" href="{% url 'FoodTaster:ingredient-list' %}">Ingrediente</a>
                <a class="navbar-brand" href="{% url 'FoodTaster:search-recipe' %}">Buscar Recetas</a>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Bienvenido al blog de Recetas</h1>
                            <div class="text-lg-start text-white">
                                {% block FoodTaster_content %}

                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Terms of Use</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Privacy Policy</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2022. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'FoodTaster/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/ingredient_detail.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<p><h3 class="mb-1 ms-xl-1">Ingrediente</h3></p>
<h5>Nombre : {{ ingredient.name }}</h5>
<p><small>{{ ingredient.description }}</small></p>

<div>
    <p><a class="btn btn-primary" href="{% url 'FoodTaster:ingredient-add' %}">Agregar otro ingrediente</a></p>
</div>

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/ingredient_list.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<h2>Lista de Ingredientes existentes</h2>
<hr></hr>

<ul>
    {% for ingredient in ingredients %}
    <li class="list-group list-group-horizontal">
        <p style="background-color: #050505b1; border-color: black; border-radius: 0.5%;">
        <p>{{ingredient.name}}</p>
        (
        <a href="{% url 'FoodTaster:dish-detail' dish.id %}">
            <i class="fa fa-eye" style="color: rgb(255, 255, 255); "> </i>
        </a>
        )
        </p>
    </li>
    {% endfor %}
</ul>

<a class="card_custom" href="{% url 'FoodTaster:ingredient-add' %}">Crear nuevo Ingrediente</a>

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/recipe_detail.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<p><h3 class="mb-1 ms-xl-1">Recetas</h3></p>

<div>
    <p><a class="btn2 btn-primary" href="{% url 'FoodTaster:recipe-add' recipe.id %}">Agregar receta</a></p>
</div>

{% if recipes %}
    <ul>
        {% for recipe in recipes %}
            <li>
                <h3>Nombre : {{ recipe.name }}</h3>
                <p style="background-color: #050505b1; border-color: black; border-radius: 0.5%;">
                    {{ recipe.description }}
                </p>
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/recipe_list.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<h2>Lista de Recetas para el plato: {{ dish.name }}</h2>
<hr></hr>

<ul>
    {% for recipe in Recipes %}
    <li class="list-group list-group-horizontal">
        <p style="background-color: #050505b1; border-color: black; border-radius: 0.5%;">
        <a href="{% url 'FoodTaster:recipe-detail' recipe.id %}">{{recipe.name}}</a>
        (
        <a href="{% url 'FoodTaster:recipe-detail' recipe.id %}">
            <i class="fa fa-eye" style="color: rgb(255, 255, 255); "> </i>
        </a>
        )
        </p>
    </li>
    {% endfor %}
</ul>

<a class="card_custom" href="{% url 'FoodTaster:recipe-add' %}">Crear nuevo Plato</a>

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/recipesForm.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<h2>{{ form_title }}</h2>
<hr></hr>

<div><p>{{ form_description }}</p></div>

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_p }}
    </table>

    <input type="submit" class="btn btn-primary" value="Confirmar"/>
</form>

{% endblock %}

Entrega1AberoCavalli/FoodTaster/templates/FoodTaster/searchRecipes.html
{% extends "FoodTaster/index.html" %}
{% load static %}
{% block FoodTaster_content %}

<h2>Buscador de recetas</h2>
<hr></hr>

<form action="/FoodTaster/search-recipes" method="GET">
    <div>
        <input type="text" name="text_search" id="recipe_name" placeholder="Busqueda por nombre">
        <input type="submit" value="Buscar por Nombre">
    </div>
</form>

{% if recipes %}
    <ul>
        {% for recipe in recipes %}
            <li>
                <h4>Nombre : {{ recipe.name }}</h4>
                <p><br><small>{{ recipe.description }}</small></p>
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}